package lastgo;
// Generated Dec 18, 2011 2:08:44 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Records generated by hbm2java
 */
public class Records  implements java.io.Serializable {


     private Integer recid;
     private User user;
     private Double latitude;
     private Double longitude;
     private Date time;
     private String type;
     private String comments;
     private byte[] image;

    public Records() {
    }

    public Records(User user, Double latitude, Double longitude, Date time, String type, String comments, byte[] image) {
       this.user = user;
       this.latitude = latitude;
       this.longitude = longitude;
       this.time = time;
       this.type = type;
       this.comments = comments;
       this.image = image;
    }
   
    public Integer getRecid() {
        return this.recid;
    }
    
    public void setRecid(Integer recid) {
        this.recid = recid;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


