package lastgo;
// Generated Dec 18, 2011 2:08:44 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable
{


     private Integer id;
     private String username;
     private String password;
     private String email;
     private Set<Records> recordses = new HashSet<Records>(0);

    public User()
    {
    }

    public User(String username, String password, String email, Set<Records> recordses)
    {
       this.username = username;
       this.password = password;
       this.email = email;
       this.recordses = recordses;
    }

        public User(String username, String password, String email)
    {
       this.username = username;
       this.password = password;
       this.email = email;
    }



    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Records> getRecordses() {
        return this.recordses;
    }
    
    public void setRecordses(Set<Records> recordses) {
        this.recordses = recordses;
    }




}


